import Tolerance from "./Tolerance.js"

export default class Tree {
    /** This class encompases a tree object. */
    
    constructor(position, reproductionInterval) {
        this.position = position
        this.height = 0 // TO DO ...
        this.diameter = 0 // TO DO ...
        this.stress = 0 // TO DO ...
        this.age = 0 // TO DO ...
        this.biodiversityReductionFactor = JSON.parse(
            process.env.NEXT_PUBLIC_BD_REDUCTION
        )
    }

    computeBiodiversityReduction() {
        // TO DO ...
    }

    computeVolume() {
        // TO DO ...
    }

    updateStress() {
        // TO DO ...
    }

    computeGrowthRate() {
        // TO DO ...
    }

    grow() {
        // TO DO ...
    }

    absorbCO2() {
        // TO DO ...
    }

    growOlder() {
        // TO DO ...
    }

    getLifeStage() {
        // TO DO ...
    }

    live() {
        // TO DO ...
    }

    decay() {
        // TO DO ...
    }

    reproduce() {
        // TO DO ...
    }
}

export class Coniferous extends Tree {
    /** This class embodies a coniferous tree. */
    
    constructor(position) {
        super(position)
        this.maxHeight = 0 // TO DO ...
        this.maxDiameter = 0 // TO DO ...
        this.reproductionInterval = 0 // TO DO ...
        this.woodDensity = 0 // TO DO ...
        this.maxAge = 0 // TO DO ...
        this.stressors = {
            temperature: {
                premature: new Tolerance(), // TO DO ...
                mature: new Tolerance() // TO DO ...
            },
            co2: {
                premature: new Tolerance(), // TO DO ...
                mature: new Tolerance() // TO DO ...
            }
        }
    }
}

export class Deciduous extends Tree {
    /** This class embodies a coniferous tree. */
    
    constructor(position) {
        super(position)
        this.maxHeight = 0 // TO DO ...
        this.maxDiameter = 0 // TO DO ...
        this.reproductionInterval = 0 // TO DO ...
        this.woodDensity = 0 // TO DO ...
        this.maxAge = 0 // TO DO ...
        this.stressors = {
            temperature: {
                premature: new Tolerance(), // TO DO ...
                mature: new Tolerance() // TO DO ...
            },
            co2: {
                premature: new Tolerance(), // TO DO ...
                mature: new Tolerance() // TO DO ...
            }
        }
    }
}